[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = ""
authors = ["Carlos Capote PÃ©rez-Andreu <carlos.capote@hawara.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
